[package]
name = "distributed_encrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.3.22",features = ["cargo","derive"]}
rand = "0.8.5"
sha3 = "0.10.8"
